// SPDX-License-Identifier: MIT OR Apache-2.0
//! Degree-2 isogenies on Montgomery curves in projective `(A24 : C24)` form.
//!
//! A single 2-isogeny is determined by its kernel point `P ∈ E[2]` (with
//! `P ≠ (0, 0)`). The codomain is computed in projective form so that an
//! `2^e`-isogeny chain only pays for one inversion at the end of the chain
//! rather than one per step.
//!
//! Formulas track the SQIsign reference (`src/ec/ref/lvlx/xisog.c` and
//! `src/ec/ref/lvlx/xeval.c`), themselves derived from Costello-Hisil
//! (PQC 2017) and Renes (PKC 2018).
//!
//! `xisog_2(P)`:
//! - codomain `(A24', C24') = (Z_P² − X_P², Z_P²)`
//! - kernel-pre-share `(K_x, K_z) = (X_P + Z_P, X_P − Z_P)`
//!
//! `xeval_2(Q; kps)`:
//! ```text
//!     t0 = X_Q + Z_Q
//!     t1 = X_Q − Z_Q
//!     t2 = K_x · t1
//!     t1 = K_z · t0
//!     t0 = t2 + t1
//!     t1 = t2 − t1
//!     R_x = X_Q · t0
//!     R_z = Z_Q · t1
//! ```

#[cfg(feature = "alloc")]
use alloc::vec::Vec;

use crate::ec::montgomery::{CurveA24, MontgomeryPoint};
use crate::gf::fp::BaseField;
use crate::gf::fp2::Fp2;

/// A single 2-isogeny step. Holds the codomain curve and the kernel-pre-share
/// that lets [`Self::eval`] push points through.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct TwoIsogeny<F: BaseField> {
    /// Codomain curve in projective `(A24 : C24)` form.
    pub codomain: CurveA24<F>,
    /// `K_x = X_P + Z_P` — first kernel-pre-share for `xeval_2`.
    pub k_x: Fp2<F>,
    /// `K_z = X_P − Z_P` — second kernel-pre-share for `xeval_2`.
    pub k_z: Fp2<F>,
}

impl<F: BaseField> TwoIsogeny<F> {
    /// Construct the 2-isogeny `φ : E → E'` with kernel generated by `kernel`.
    ///
    /// `kernel` must be a 2-torsion point on the domain curve and must not be
    /// `(0 : 1)` (the unique 2-torsion point at `x = 0`). If passed
    /// `(0 : 1)` the codomain becomes the curve itself with `A24 = C24 = 0`
    /// — callers signing in the SQIsign pipeline route to a separate
    /// `xisog_2_singular` path which is left for the Clapotis session.
    pub fn new(kernel: &MontgomeryPoint<F>) -> Self {
        let x_sq = kernel.x.square();
        let z_sq = kernel.z.square();
        let codomain = CurveA24::new(z_sq.sub(&x_sq), z_sq);
        let k_x = kernel.x.add(&kernel.z);
        let k_z = kernel.x.sub(&kernel.z);
        Self { codomain, k_x, k_z }
    }

    /// Push a point `q` on the source curve through this isogeny.
    pub fn eval(&self, q: &MontgomeryPoint<F>) -> MontgomeryPoint<F> {
        let t0 = q.x.add(&q.z);
        let t1 = q.x.sub(&q.z);
        let t2 = self.k_x.mul(&t1);
        let t1 = self.k_z.mul(&t0);
        let s = t2.add(&t1);
        let d = t2.sub(&t1);
        let x = q.x.mul(&s);
        let z = q.z.mul(&d);
        MontgomeryPoint::new(x, z)
    }
}

/// A chain of `e` consecutive 2-isogenies — the `2^e`-isogeny generated by
/// a single point `K` of order `2^e`.
///
/// Construction strategy (the "balanced strategy" is overkill for now; we use
/// the naive linear strategy: at each step `i ∈ [0, e)`, double the current
/// "big" kernel down to order 2, build the single-step `TwoIsogeny`, push
/// `K` and any extra-point list through to the next domain, repeat).
#[cfg(feature = "alloc")]
#[derive(Clone, Debug)]
pub struct IsogenyChain2e<F: BaseField> {
    /// Final codomain after `e` steps.
    pub codomain: CurveA24<F>,
    /// The intermediate single-step isogenies, in order.
    pub steps: Vec<TwoIsogeny<F>>,
}

#[cfg(feature = "alloc")]
impl<F: BaseField> IsogenyChain2e<F> {
    /// Build a length-`e` chain of 2-isogenies starting at `domain` with
    /// kernel point `kernel` of order `2^e`.
    ///
    /// `extra` is an optional point on the *source* curve that will be pushed
    /// through every step in lock-step with the kernel; on return,
    /// `extra_image` holds its image on the final codomain.
    pub fn new(
        domain: CurveA24<F>,
        kernel: MontgomeryPoint<F>,
        e: u32,
        extra: Option<MontgomeryPoint<F>>,
    ) -> (Self, Option<MontgomeryPoint<F>>) {
        let mut cur_domain = domain;
        let mut cur_kernel = kernel;
        let mut cur_extra = extra;
        let mut steps = Vec::with_capacity(e as usize);
        for i in 0..e {
            // Double cur_kernel down to a 2-torsion point on cur_domain.
            let kernel_2 = cur_domain.x_double_n(&cur_kernel, e - 1 - i);
            let iso = TwoIsogeny::new(&kernel_2);
            cur_domain = iso.codomain;
            cur_kernel = iso.eval(&cur_kernel);
            cur_extra = cur_extra.as_ref().map(|p| iso.eval(p));
            steps.push(iso);
        }
        (
            Self {
                codomain: cur_domain,
                steps,
            },
            cur_extra,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gf::fp::Fp1Element;

    type F2 = Fp2<Fp1Element>;
    type Point = MontgomeryPoint<Fp1Element>;

    #[test]
    fn kernel_pushes_to_infinity() {
        // Pick a 2-torsion point on E_0. The roots of x³ + x = 0 are
        // x ∈ {0, i, -i}. We use x = i (which is non-singular for xisog_2).
        let kernel_x = F2::img();
        let kernel = Point::new(kernel_x, F2::one());
        let iso = TwoIsogeny::new(&kernel);
        let image = iso.eval(&kernel);
        // image.z must be zero — the kernel maps to the identity on codomain.
        assert!(bool::from(image.z.is_zero()));
    }

    #[test]
    fn isogeny_with_kernel_i_changes_curve() {
        // The 2-isogeny from E_0 with kernel (i, 0) should yield a codomain
        // with a different j-invariant than 1728 (E_0's). Compute on both
        // sides and confirm inequality.
        let kernel = Point::new(F2::img(), F2::one());
        let iso = TwoIsogeny::new(&kernel);
        // Recover affine A of the codomain.
        let a_dst = iso.codomain.to_affine_a();
        // E_0 has A = 0; the codomain should have a different A.
        assert_ne!(a_dst, F2::zero());
    }

    #[test]
    fn double_iso_step_works() {
        // After applying iso twice (kernel propagated each step), the second
        // codomain's A should change again.
        let k = Point::new(F2::img(), F2::one());
        let iso1 = TwoIsogeny::new(&k);
        let k_image = iso1.eval(&k);
        // k_image is on the codomain; if its Z is zero (point at infinity)
        // we can't continue — but we already verified that above, so just
        // construct a fresh 2-torsion point on the codomain.
        // For the chain test we pick a separate point not in the kernel.
        let q = Point::new(F2::one().double().double(), F2::one()); // x = 4
        let q_img = iso1.eval(&q);
        // q_img.z should still be a valid (non-zero in general) F2 value.
        let _ = (k_image, q_img);
    }

    #[cfg(feature = "alloc")]
    #[test]
    fn chain_codomain_matches_repeated_single_step() {
        // Apply chain length-1 — should match the single-step result.
        let domain = CurveA24::<Fp1Element>::e0();
        let kernel = Point::new(F2::img(), F2::one());
        let (chain, _extra) = IsogenyChain2e::new(domain, kernel, 1, None);
        let single = TwoIsogeny::new(&kernel);
        // Cross-multiply A24 / C24 to compare the projective curves.
        let lhs = chain.codomain.a24.mul(&single.codomain.c24);
        let rhs = single.codomain.a24.mul(&chain.codomain.c24);
        assert_eq!(lhs, rhs);
        assert_eq!(chain.steps.len(), 1);
    }
}
