// SPDX-License-Identifier: MIT OR Apache-2.0
//! Multiplication of left `O_0`-ideals.
//!
//! Given two integral left `O_0`-ideals `I, J` with `Z`-bases `{e_1, e_2,
//! e_3, e_4}` and `{f_1, f_2, f_3, f_4}` (each `O_0` element stored in
//! `O_0`-basis coordinates), the product ideal `I · J` is the
//! `Z`-submodule of `O_0` generated by the 16 pairwise products
//! `{e_i · f_j : 1 ≤ i, j ≤ 4}`.
//!
//! Construction:
//!
//! 1. Form the 16×4 matrix whose rows are `(e_i · f_j)` in `O_0`-basis
//!    coordinates, via [`super::o0_mul::multiply_o0_basis`].
//! 2. HNF-reduce that matrix to upper-triangular form; the top 4 rows are
//!    the canonical basis of `I · J`.
//!
//! Norm-preservation as a sanity invariant: `N(I · J) = N(I) · N(J)` for
//! integral ideals in a maximal order.

use crypto_bigint::{Int, Uint};

use crate::quaternion::hnf::hnf_rect_4cols;
use crate::quaternion::ideal::LeftIdeal;
use crate::quaternion::o0_mul::multiply_o0_basis;

/// Right-multiply a left ideal `I` by a single quaternion `α` (in
/// `O_0`-basis coords): returns the left ideal `I · α` whose `Z`-basis is
/// `{e_k · α : e_k ∈ basis(I)}`, HNF-reduced.
///
/// Norm identity: `N(I·α) = N(I) · N_red(α)²`. (The right-multiplication
/// map `O_0 → O_0` has determinant `N_red(α)²`; multiplied by the basis
/// determinant of `I` gives the ideal norm of `I·α`.)
#[allow(clippy::needless_range_loop)]
pub fn ideal_right_multiply<const LIMBS: usize>(
    i: &LeftIdeal<LIMBS>,
    alpha: &[Int<LIMBS>; 4],
    p: &Uint<LIMBS>,
) -> LeftIdeal<LIMBS> {
    let zero = Int::<LIMBS>::from_i64(0);
    let mut basis = [[zero; 4]; 4];
    for k in 0..4 {
        basis[k] = multiply_o0_basis(&i.basis[k], alpha, p);
    }
    let reduced = crate::quaternion::hnf::hnf_4x4(&basis);
    LeftIdeal::new(reduced)
}

/// Right-multiply a left ideal `I` by the rational quaternion
/// `α_rational = α_coord / α_denom`, returning the left ideal
/// `I · α_rational`. The integer basis matrix is `I.basis · M_{α_coord}`
/// (just like [`ideal_right_multiply`]); the denominator is multiplied
/// by `α_denom`; and the cached norm is updated via the SQIsign C
/// reference's `quat_lideal_mul` identity:
///
/// ```text
///     N(I · α_rational) = N(I) · N_red(α_coord) / α_denom²
/// ```
///
/// where `N_red(α_coord)` is the integer reduced norm of the
/// `O_0`-basis coordinate vector `α_coord` (computed via
/// [`super::o0_mul::reduced_norm_o0_basis`]).
///
/// `caller_provided_new_norm`, when `Some`, overrides the formula and
/// uses the caller's value — useful when KLPT's prime-norm search has
/// already computed `N(J) = q` from the prime-acceptance test and
/// wants to skip the redundant arithmetic.
///
/// Returns `None` if any of the divisibility / norm-update integer
/// divisions aren't exact, indicating an invariant violation.
#[allow(clippy::needless_range_loop)]
pub fn ideal_right_multiply_rational<const LIMBS: usize>(
    i: &LeftIdeal<LIMBS>,
    alpha_coord: &[Int<LIMBS>; 4],
    alpha_denom: &Uint<LIMBS>,
    p: &Uint<LIMBS>,
    caller_provided_new_norm: Option<Uint<LIMBS>>,
) -> Option<LeftIdeal<LIMBS>> {
    let zero = Int::<LIMBS>::from_i64(0);
    let mut basis = [[zero; 4]; 4];
    for k in 0..4 {
        basis[k] = multiply_o0_basis(&i.basis[k], alpha_coord, p);
    }
    let reduced = crate::quaternion::hnf::hnf_4x4(&basis);
    let new_denom = i.denom.wrapping_mul(alpha_denom);

    let new_norm = match caller_provided_new_norm {
        Some(n) => n,
        None => {
            // N_red(α_coord), then multiply by N(I), then divide by α_denom².
            let n_red_alpha_int = crate::quaternion::o0_mul::reduced_norm_o0_basis(alpha_coord, p);
            let n_red_alpha = n_red_alpha_int.abs();
            let numerator = i.cached_norm.wrapping_mul(&n_red_alpha);
            let denom_sq = alpha_denom.wrapping_mul(alpha_denom);
            let denom_sq_nz =
                Option::<crypto_bigint::NonZero<_>>::from(crypto_bigint::NonZero::new(denom_sq))?;
            let (q, rem) = numerator.div_rem_vartime(&denom_sq_nz);
            if rem != Uint::<LIMBS>::from_u64(0) {
                return None;
            }
            q
        }
    };

    Some(LeftIdeal::with_denom_and_norm(reduced, new_denom, new_norm))
}

/// Wide-Int variant of [`ideal_right_multiply_rational`]. Performs the
/// inner `multiply_o0_basis` calls at `WIDE` precision via
/// [`super::o0_mul::multiply_o0_basis_wide`], avoiding overflow when
/// the ideal's basis entries are O(p) — the regime where the narrow
/// rational right-multiply (S49) would wrap.
///
/// The final basis entries (after multiplication and HNF) must still
/// fit in `Int<NARROW>` (here pinned to `Int<8>` for compatibility
/// with the rest of the prototype). For ideals of moderate norm at L1,
/// L3, L5 this is satisfied because the rational basis `(basis/denom)`
/// has bounded entries even when the integer numerator grows.
///
/// `caller_provided_new_norm` overrides the C-reference formula
/// `N(I)·N_red(α)/α_denom²` — KLPT callers supply `Some(q)` from the
/// primality test to skip redundant arithmetic.
#[allow(clippy::needless_range_loop)]
pub fn ideal_right_multiply_rational_wide<const WIDE: usize>(
    i: &LeftIdeal<8>,
    alpha_coord: &[Int<8>; 4],
    alpha_denom: &Uint<8>,
    p: &Uint<8>,
    caller_provided_new_norm: Option<Uint<8>>,
) -> Option<LeftIdeal<8>> {
    use crate::quaternion::o0_mul::multiply_o0_basis_wide;
    let zero = Int::<8>::from_i64(0);
    let mut basis = [[zero; 4]; 4];
    for k in 0..4 {
        basis[k] = multiply_o0_basis_wide::<8, WIDE>(&i.basis[k], alpha_coord, p);
    }
    let reduced = crate::quaternion::hnf::hnf_4x4(&basis);
    let new_denom = i.denom.wrapping_mul(alpha_denom);

    let new_norm = match caller_provided_new_norm {
        Some(n) => n,
        None => {
            // Auto-compute via the SQIsign C reference's formula
            // `N(I·β) = N(I) · N_red(β_coord) / β_denom²` at WIDE
            // precision, then narrow result to Uint<8>.
            let n_red_alpha_w: Int<WIDE> =
                crate::quaternion::o0_mul::reduced_norm_o0_basis_wide::<8, WIDE>(alpha_coord, p);
            let n_red_alpha_w_u: Uint<WIDE> = n_red_alpha_w.abs();
            let cached_norm_w: Uint<WIDE> = i.cached_norm.resize::<WIDE>();
            let numerator_w = cached_norm_w.wrapping_mul(&n_red_alpha_w_u);
            let alpha_denom_w: Uint<WIDE> = alpha_denom.resize::<WIDE>();
            let denom_sq_w = alpha_denom_w.wrapping_mul(&alpha_denom_w);
            let denom_sq_nz_w: crypto_bigint::NonZero<Uint<WIDE>> =
                Option::<crypto_bigint::NonZero<_>>::from(crypto_bigint::NonZero::new(denom_sq_w))?;
            let (q_w, rem_w) = numerator_w.div_rem_vartime(&denom_sq_nz_w);
            if rem_w != Uint::<WIDE>::from_u64(0) {
                return None;
            }
            q_w.resize::<8>()
        }
    };

    Some(LeftIdeal::with_denom_and_norm(reduced, new_denom, new_norm))
}

/// Left ideal whose cached norm is tracked at independent precision
/// `NLIMBS`, decoupled from the basis's `Int<8>` precision.
///
/// At L5 scale and beyond, the canonical KLPT-body output norm
/// `N(K) = q · target_m` can exceed `Uint<8>`'s 512-bit ceiling. The
/// existing [`LeftIdeal<8>`] stores `cached_norm` at `Uint<8>`, which
/// silently truncates wide norms. `LeftIdealWideNorm<NLIMBS>` lifts
/// the cached-norm storage to `Uint<NLIMBS>`, leaving the basis at
/// `Int<8>` (the prototype's narrow regime; basis entries at L1/L3/L5
/// fit narrow because they're bounded by `√(cached_norm)` not by
/// `cached_norm` itself).
///
/// The `inner.cached_norm` field is set but should be considered
/// LOSSY — the authoritative cached norm is the explicit
/// `cached_norm: Uint<NLIMBS>` field. Operations that need the
/// authoritative value should read `WideIdealNorm.cached_norm`, not
/// `WideIdealNorm.inner.cached_norm`.
///
/// This is the S75 structural fix unblocking the L5 KLPT body.
#[derive(Debug, Clone)]
pub struct LeftIdealWideNorm<const NLIMBS: usize> {
    /// Underlying left ideal with basis at `Int<8>`. The inner
    /// `cached_norm: Uint<8>` is LOSSY when the true norm exceeds
    /// `Uint<8>`; consult `LeftIdealWideNorm.cached_norm` instead.
    pub inner: LeftIdeal<8>,
    /// Authoritative cached norm at `Uint<NLIMBS>` precision.
    pub cached_norm: Uint<NLIMBS>,
}

impl<const NLIMBS: usize> LeftIdealWideNorm<NLIMBS> {
    /// Construct from a `LeftIdeal<8>` with an explicit wide cached norm.
    /// Caller's `cached_norm` is the authoritative value; the inner
    /// `LeftIdeal<8>`'s narrow `cached_norm` is preserved for
    /// compatibility but should not be trusted for wide-norm operations.
    pub const fn new(inner: LeftIdeal<8>, cached_norm: Uint<NLIMBS>) -> Self {
        Self { inner, cached_norm }
    }

    /// Bridge from a narrow `LeftIdeal<8>` to `LeftIdealWideNorm<NLIMBS>`
    /// by widening the inner cached_norm via `resize`. Use when starting
    /// from a small ideal (e.g., `O_0` with `N = 1`) before composing
    /// with wide-norm operations.
    pub fn from_narrow(inner: LeftIdeal<8>) -> Self {
        let cached_norm = inner.cached_norm.resize::<NLIMBS>();
        Self { inner, cached_norm }
    }
}

/// Compute `I · J` as a left `O_0`-ideal in canonical HNF form.
pub fn ideal_multiply<const LIMBS: usize>(
    i: &LeftIdeal<LIMBS>,
    j: &LeftIdeal<LIMBS>,
    p: &Uint<LIMBS>,
) -> LeftIdeal<LIMBS> {
    let zero = Int::<LIMBS>::from_i64(0);
    let mut products: [[Int<LIMBS>; 4]; 16] = [[zero; 4]; 16];
    let mut idx = 0;
    for ei in &i.basis {
        for fj in &j.basis {
            products[idx] = multiply_o0_basis(ei, fj, p);
            idx += 1;
        }
    }
    // Reduce 16×4 → upper-triangular; top 4 rows are I·J's HNF basis.
    let reduced = hnf_rect_4cols::<16, LIMBS>(&products);
    let mut basis = [[zero; 4]; 4];
    basis[..4].copy_from_slice(&reduced[..4]);
    LeftIdeal::new(basis)
}

#[cfg(test)]
mod tests {
    use super::*;

    type Ideal = LeftIdeal<8>;

    #[test]
    fn rational_wide_auto_norm_matches_caller_provided() {
        // Auto-norm-compute path: when `caller_provided_new_norm` is
        // None, the function computes `N(I)·N_red(α)/α_denom²` at WIDE
        // precision. This should match a known case where the caller
        // provided the same value.
        //
        // Use a simple integer ideal: I = 2·O_0 at fake-prime p=7,
        // α = (1, 0, 0, 0) (= 1 in O_0), α_denom = 1.
        // N_red(α) = 1, so N(I·α) = N(I)·1/1 = N(I) = 16.
        let p = Uint::<8>::from_u64(7);
        let two_id = Ideal::full_order().scale(2);
        let alpha_one = [
            Int::<8>::from_i64(1),
            Int::<8>::from_i64(0),
            Int::<8>::from_i64(0),
            Int::<8>::from_i64(0),
        ];
        let alpha_denom = Uint::<8>::from_u64(1);

        // Auto-compute path (caller_provided_new_norm = None):
        let j_auto =
            ideal_right_multiply_rational_wide::<16>(&two_id, &alpha_one, &alpha_denom, &p, None)
                .expect("auto-norm path returns Some on valid input");

        // Caller-provided path with N(I) = 16:
        let j_explicit = ideal_right_multiply_rational_wide::<16>(
            &two_id,
            &alpha_one,
            &alpha_denom,
            &p,
            Some(Uint::<8>::from_u64(16)),
        )
        .expect("explicit-norm path returns Some on valid input");

        // Both paths must agree on the cached norm.
        assert_eq!(j_auto.norm(), j_explicit.norm());
        assert_eq!(j_auto.norm(), Uint::<8>::from_u64(16));
        // And on the basis (HNF-reduced).
        assert_eq!(j_auto.basis, j_explicit.basis);
    }

    fn z() -> Int<8> {
        Int::<8>::from_i64(0)
    }
    fn n(v: i64) -> Int<8> {
        Int::<8>::from_i64(v)
    }
    fn fake_p() -> Uint<8> {
        Uint::<8>::from_u64(7)
    }

    #[test]
    fn o0_times_o0_is_o0() {
        let id = Ideal::full_order();
        let prod = ideal_multiply(&id, &id, &fake_p());
        // O_0 · O_0 = O_0 — the product should be lattice-equal to O_0.
        assert!(prod.equals_lattice(&id));
        assert_eq!(prod.norm(), Uint::<8>::from_u64(1));
    }

    #[test]
    fn o0_times_two_o0_is_two_o0() {
        let id = Ideal::full_order();
        let two_id = id.scale(2);
        let prod = ideal_multiply(&id, &two_id, &fake_p());
        // O_0 · 2·O_0 = 2·O_0; norm 16.
        assert!(prod.equals_lattice(&two_id));
        assert_eq!(prod.norm(), Uint::<8>::from_u64(16));
    }

    #[test]
    fn product_norm_multiplies() {
        // N(I·J) = N(I) · N(J) when both ideals are integral.
        // 3·O_0 has norm 81; 5·O_0 has norm 625; product has norm 81·625 = 50625.
        let three_id = Ideal::full_order().scale(3);
        let five_id = Ideal::full_order().scale(5);
        let prod = ideal_multiply(&three_id, &five_id, &fake_p());
        assert_eq!(prod.norm(), Uint::<8>::from_u64(81 * 625));
    }

    #[test]
    fn product_basis_in_both_factors_image() {
        // Every basis vector of I·J should be representable in O_0 (since I·J ⊆ O_0).
        // Trivial: the full-order test ensures this — using `contains` we can
        // confirm every basis vector lives in O_0 (vacuous but smoke-tests
        // the assembled pipeline).
        let two_id = Ideal::full_order().scale(2);
        let three_id = Ideal::full_order().scale(3);
        let prod = ideal_multiply(&two_id, &three_id, &fake_p());
        // 2·O_0 · 3·O_0 = 6·O_0; norm 6^4 = 1296.
        assert_eq!(prod.norm(), Uint::<8>::from_u64(1296));
        let six_id = Ideal::full_order().scale(6);
        assert!(prod.equals_lattice(&six_id));
        // The basis vectors of prod are all in O_0 (trivially — they ARE O_0
        // elements). Smoke-test via `contains`.
        let full = Ideal::full_order();
        for row in &prod.basis {
            assert!(full.contains(row));
        }
    }

    #[test]
    fn right_multiply_by_one_is_identity() {
        let id = Ideal::full_order();
        let one = [n(1), z(), z(), z()];
        let result = ideal_right_multiply(&id, &one, &fake_p());
        assert!(result.equals_lattice(&id));
    }

    #[test]
    fn right_multiply_full_order_by_alpha_is_principal_alpha() {
        // O_0 · α (right-multiply) should equal the principal left ideal O_0·α.
        let id = Ideal::full_order();
        let alpha = [z(), z(), z(), n(1)]; // e_3
        let p = fake_p();
        let from_right_mul = ideal_right_multiply(&id, &alpha, &p);
        let from_principal = crate::quaternion::o0_mul::principal_left_ideal_from_o0(&alpha, &p);
        assert!(from_right_mul.equals_lattice(&from_principal));
        assert_eq!(from_right_mul.norm(), Uint::<8>::from_u64(4));
    }

    #[test]
    fn right_multiply_norm_identity() {
        // N(I · α) = N(I) · N_red(α)².
        let p = fake_p();
        let id = Ideal::full_order().scale(2); // N(I) = 16
        let alpha = [z(), z(), z(), n(1)]; // N_red(α) = 2 at p=7
        let result = ideal_right_multiply(&id, &alpha, &p);
        // Expected: 16 · 4 = 64.
        assert_eq!(result.norm(), Uint::<8>::from_u64(64));
    }

    #[test]
    fn right_multiply_by_zero_is_zero() {
        let id = Ideal::full_order();
        let zero_q = [z(); 4];
        let result = ideal_right_multiply(&id, &zero_q, &fake_p());
        for row in &result.basis {
            for cell in row {
                assert_eq!(*cell, z());
            }
        }
    }

    #[test]
    fn ideal_multiply_zero_is_zero() {
        // Multiplying by the zero ideal (basis = all zeros) yields the zero ideal.
        let id = Ideal::full_order();
        let zero_ideal = Ideal::new([[z(); 4]; 4]);
        let prod = ideal_multiply(&id, &zero_ideal, &fake_p());
        for row in &prod.basis {
            for cell in row {
                assert_eq!(*cell, z());
            }
        }
    }

    #[test]
    fn principal_ideal_norm_equals_quaternion_norm() {
        // Construct a "principal" left ideal O_0 · γ where γ = (0, 0, 0, 1) = e_3
        // by left-multiplying each basis vector by e_3. Then its norm should
        // equal N_red(e_3)² (the reduced norm squared, since the ideal-norm is
        // [O_0 : O_0·γ] = N_red(γ)² for principal ideals in a maximal order).
        //
        // For p=7: N_red(e_3) = N((1+k)/2) = (1 + p)/4 = 2. So ideal norm = 4.
        let id = Ideal::full_order();
        let gamma = [z(), z(), z(), n(1)]; // e_3
        let p = fake_p();
        // Build the principal ideal by multiplying each O_0 basis vector by γ.
        let mut basis = [[z(); 4]; 4];
        for (k, row) in basis.iter_mut().enumerate() {
            let mut e = [z(); 4];
            e[k] = n(1);
            *row = multiply_o0_basis(&e, &gamma, &p);
        }
        let principal = Ideal::new(basis);
        // Norm should be (N_red(e_3))² = 4.
        assert_eq!(principal.norm(), Uint::<8>::from_u64(4));
        // And p_id = id · γ_id; compose via ideal_multiply for comparison.
        let gamma_id = Ideal::new([
            multiply_o0_basis(&[n(1), z(), z(), z()], &gamma, &p),
            multiply_o0_basis(&[z(), n(1), z(), z()], &gamma, &p),
            multiply_o0_basis(&[z(), z(), n(1), z()], &gamma, &p),
            multiply_o0_basis(&[z(), z(), z(), n(1)], &gamma, &p),
        ]);
        let composed = ideal_multiply(&id, &gamma_id, &p);
        assert!(principal.equals_lattice(&composed));
    }
}
