// SPDX-License-Identifier: MIT OR Apache-2.0
//! Multiplication of left `O_0`-ideals.
//!
//! Given two integral left `O_0`-ideals `I, J` with `Z`-bases `{e_1, e_2,
//! e_3, e_4}` and `{f_1, f_2, f_3, f_4}` (each `O_0` element stored in
//! `O_0`-basis coordinates), the product ideal `I · J` is the
//! `Z`-submodule of `O_0` generated by the 16 pairwise products
//! `{e_i · f_j : 1 ≤ i, j ≤ 4}`.
//!
//! Construction:
//!
//! 1. Form the 16×4 matrix whose rows are `(e_i · f_j)` in `O_0`-basis
//!    coordinates, via [`super::o0_mul::multiply_o0_basis`].
//! 2. HNF-reduce that matrix to upper-triangular form; the top 4 rows are
//!    the canonical basis of `I · J`.
//!
//! Norm-preservation as a sanity invariant: `N(I · J) = N(I) · N(J)` for
//! integral ideals in a maximal order.

use crypto_bigint::{Int, Uint};

use crate::quaternion::hnf::hnf_rect_4cols;
use crate::quaternion::ideal::LeftIdeal;
use crate::quaternion::o0_mul::multiply_o0_basis;

/// Right-multiply a left ideal `I` by a single quaternion `α` (in
/// `O_0`-basis coords): returns the left ideal `I · α` whose `Z`-basis is
/// `{e_k · α : e_k ∈ basis(I)}`, HNF-reduced.
///
/// Norm identity: `N(I·α) = N(I) · N_red(α)²`. (The right-multiplication
/// map `O_0 → O_0` has determinant `N_red(α)²`; multiplied by the basis
/// determinant of `I` gives the ideal norm of `I·α`.)
#[allow(clippy::needless_range_loop)]
pub fn ideal_right_multiply<const LIMBS: usize>(
    i: &LeftIdeal<LIMBS>,
    alpha: &[Int<LIMBS>; 4],
    p: &Uint<LIMBS>,
) -> LeftIdeal<LIMBS> {
    let zero = Int::<LIMBS>::from_i64(0);
    let mut basis = [[zero; 4]; 4];
    for k in 0..4 {
        basis[k] = multiply_o0_basis(&i.basis[k], alpha, p);
    }
    let reduced = crate::quaternion::hnf::hnf_4x4(&basis);
    LeftIdeal::new(reduced)
}

/// Compute `I · J` as a left `O_0`-ideal in canonical HNF form.
pub fn ideal_multiply<const LIMBS: usize>(
    i: &LeftIdeal<LIMBS>,
    j: &LeftIdeal<LIMBS>,
    p: &Uint<LIMBS>,
) -> LeftIdeal<LIMBS> {
    let zero = Int::<LIMBS>::from_i64(0);
    let mut products: [[Int<LIMBS>; 4]; 16] = [[zero; 4]; 16];
    let mut idx = 0;
    for ei in &i.basis {
        for fj in &j.basis {
            products[idx] = multiply_o0_basis(ei, fj, p);
            idx += 1;
        }
    }
    // Reduce 16×4 → upper-triangular; top 4 rows are I·J's HNF basis.
    let reduced = hnf_rect_4cols::<16, LIMBS>(&products);
    let mut basis = [[zero; 4]; 4];
    basis[..4].copy_from_slice(&reduced[..4]);
    LeftIdeal::new(basis)
}

#[cfg(test)]
mod tests {
    use super::*;

    type Ideal = LeftIdeal<8>;

    fn z() -> Int<8> {
        Int::<8>::from_i64(0)
    }
    fn n(v: i64) -> Int<8> {
        Int::<8>::from_i64(v)
    }
    fn fake_p() -> Uint<8> {
        Uint::<8>::from_u64(7)
    }

    #[test]
    fn o0_times_o0_is_o0() {
        let id = Ideal::full_order();
        let prod = ideal_multiply(&id, &id, &fake_p());
        // O_0 · O_0 = O_0 — the product should be lattice-equal to O_0.
        assert!(prod.equals_lattice(&id));
        assert_eq!(prod.norm(), Uint::<8>::from_u64(1));
    }

    #[test]
    fn o0_times_two_o0_is_two_o0() {
        let id = Ideal::full_order();
        let two_id = id.scale(2);
        let prod = ideal_multiply(&id, &two_id, &fake_p());
        // O_0 · 2·O_0 = 2·O_0; norm 16.
        assert!(prod.equals_lattice(&two_id));
        assert_eq!(prod.norm(), Uint::<8>::from_u64(16));
    }

    #[test]
    fn product_norm_multiplies() {
        // N(I·J) = N(I) · N(J) when both ideals are integral.
        // 3·O_0 has norm 81; 5·O_0 has norm 625; product has norm 81·625 = 50625.
        let three_id = Ideal::full_order().scale(3);
        let five_id = Ideal::full_order().scale(5);
        let prod = ideal_multiply(&three_id, &five_id, &fake_p());
        assert_eq!(prod.norm(), Uint::<8>::from_u64(81 * 625));
    }

    #[test]
    fn product_basis_in_both_factors_image() {
        // Every basis vector of I·J should be representable in O_0 (since I·J ⊆ O_0).
        // Trivial: the full-order test ensures this — using `contains` we can
        // confirm every basis vector lives in O_0 (vacuous but smoke-tests
        // the assembled pipeline).
        let two_id = Ideal::full_order().scale(2);
        let three_id = Ideal::full_order().scale(3);
        let prod = ideal_multiply(&two_id, &three_id, &fake_p());
        // 2·O_0 · 3·O_0 = 6·O_0; norm 6^4 = 1296.
        assert_eq!(prod.norm(), Uint::<8>::from_u64(1296));
        let six_id = Ideal::full_order().scale(6);
        assert!(prod.equals_lattice(&six_id));
        // The basis vectors of prod are all in O_0 (trivially — they ARE O_0
        // elements). Smoke-test via `contains`.
        let full = Ideal::full_order();
        for row in &prod.basis {
            assert!(full.contains(row));
        }
    }

    #[test]
    fn right_multiply_by_one_is_identity() {
        let id = Ideal::full_order();
        let one = [n(1), z(), z(), z()];
        let result = ideal_right_multiply(&id, &one, &fake_p());
        assert!(result.equals_lattice(&id));
    }

    #[test]
    fn right_multiply_full_order_by_alpha_is_principal_alpha() {
        // O_0 · α (right-multiply) should equal the principal left ideal O_0·α.
        let id = Ideal::full_order();
        let alpha = [z(), z(), z(), n(1)]; // e_3
        let p = fake_p();
        let from_right_mul = ideal_right_multiply(&id, &alpha, &p);
        let from_principal = crate::quaternion::o0_mul::principal_left_ideal_from_o0(&alpha, &p);
        assert!(from_right_mul.equals_lattice(&from_principal));
        assert_eq!(from_right_mul.norm(), Uint::<8>::from_u64(4));
    }

    #[test]
    fn right_multiply_norm_identity() {
        // N(I · α) = N(I) · N_red(α)².
        let p = fake_p();
        let id = Ideal::full_order().scale(2); // N(I) = 16
        let alpha = [z(), z(), z(), n(1)]; // N_red(α) = 2 at p=7
        let result = ideal_right_multiply(&id, &alpha, &p);
        // Expected: 16 · 4 = 64.
        assert_eq!(result.norm(), Uint::<8>::from_u64(64));
    }

    #[test]
    fn right_multiply_by_zero_is_zero() {
        let id = Ideal::full_order();
        let zero_q = [z(); 4];
        let result = ideal_right_multiply(&id, &zero_q, &fake_p());
        for row in &result.basis {
            for cell in row {
                assert_eq!(*cell, z());
            }
        }
    }

    #[test]
    fn ideal_multiply_zero_is_zero() {
        // Multiplying by the zero ideal (basis = all zeros) yields the zero ideal.
        let id = Ideal::full_order();
        let zero_ideal = Ideal::new([[z(); 4]; 4]);
        let prod = ideal_multiply(&id, &zero_ideal, &fake_p());
        for row in &prod.basis {
            for cell in row {
                assert_eq!(*cell, z());
            }
        }
    }

    #[test]
    fn principal_ideal_norm_equals_quaternion_norm() {
        // Construct a "principal" left ideal O_0 · γ where γ = (0, 0, 0, 1) = e_3
        // by left-multiplying each basis vector by e_3. Then its norm should
        // equal N_red(e_3)² (the reduced norm squared, since the ideal-norm is
        // [O_0 : O_0·γ] = N_red(γ)² for principal ideals in a maximal order).
        //
        // For p=7: N_red(e_3) = N((1+k)/2) = (1 + p)/4 = 2. So ideal norm = 4.
        let id = Ideal::full_order();
        let gamma = [z(), z(), z(), n(1)]; // e_3
        let p = fake_p();
        // Build the principal ideal by multiplying each O_0 basis vector by γ.
        let mut basis = [[z(); 4]; 4];
        for (k, row) in basis.iter_mut().enumerate() {
            let mut e = [z(); 4];
            e[k] = n(1);
            *row = multiply_o0_basis(&e, &gamma, &p);
        }
        let principal = Ideal::new(basis);
        // Norm should be (N_red(e_3))² = 4.
        assert_eq!(principal.norm(), Uint::<8>::from_u64(4));
        // And p_id = id · γ_id; compose via ideal_multiply for comparison.
        let gamma_id = Ideal::new([
            multiply_o0_basis(&[n(1), z(), z(), z()], &gamma, &p),
            multiply_o0_basis(&[z(), n(1), z(), z()], &gamma, &p),
            multiply_o0_basis(&[z(), z(), n(1), z()], &gamma, &p),
            multiply_o0_basis(&[z(), z(), z(), n(1)], &gamma, &p),
        ]);
        let composed = ideal_multiply(&id, &gamma_id, &p);
        assert!(principal.equals_lattice(&composed));
    }
}
